export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_FAIL = "PROFILE_FAIL";
export const PROFILE_RESET = "PROFILE_RESET";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
